In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [4]:
!nvidia-smi

Tue Jul 18 10:03:48 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650        Off | 00000000:0A:00.0 Off |                  N/A |
| 40%   38C    P8              N/A /  75W |      3MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Introduction to Tensors

# Creating Tensors

In [5]:
# Scalar
# https://pytorch.org/docs/stable/tensors.html
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR_TWO = torch.tensor([[[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]],
                           [[11, 12, 13],
                            [21, 22, 23],
                            [31, 32, 33]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
TENSOR[0][1]

tensor([4, 5, 6])

In [20]:
TENSOR_TWO.shape

torch.Size([2, 3, 3])

# Random Tensors

In [21]:
# torch.rand
# https://pytorch.org/docs/stable/generated/torch.rand.html

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7156, 0.9217, 0.5267, 0.9579],
        [0.5134, 0.3472, 0.9213, 0.0492],
        [0.1178, 0.8999, 0.9299, 0.2509]])

In [22]:
random_tensor.ndim

random_multiple_dimesion = torch.rand(3, 4, 5, 6)
random_multiple_dimesion

tensor([[[[0.8259, 0.0949, 0.7714, 0.0662, 0.7011, 0.3963],
          [0.6912, 0.0084, 0.6994, 0.7134, 0.2436, 0.2861],
          [0.3179, 0.7763, 0.7841, 0.6388, 0.7944, 0.3913],
          [0.2762, 0.1004, 0.8799, 0.5686, 0.2737, 0.8239],
          [0.8278, 0.1383, 0.6688, 0.1684, 0.3417, 0.7745]],

         [[0.6038, 0.2725, 0.5111, 0.5440, 0.3694, 0.2759],
          [0.4157, 0.1451, 0.1232, 0.2965, 0.1274, 0.5124],
          [0.4435, 0.5734, 0.8129, 0.5076, 0.4553, 0.4820],
          [0.5272, 0.0092, 0.9046, 0.5760, 0.9010, 0.2731],
          [0.8457, 0.5757, 0.7484, 0.8221, 0.1542, 0.1599]],

         [[0.3856, 0.0013, 0.8818, 0.3791, 0.6342, 0.0643],
          [0.7115, 0.1586, 0.1152, 0.1416, 0.2061, 0.9633],
          [0.5751, 0.3016, 0.6609, 0.6968, 0.2575, 0.4997],
          [0.5961, 0.3123, 0.7279, 0.3475, 0.2767, 0.6119],
          [0.2174, 0.2103, 0.9552, 0.9091, 0.5936, 0.8744]],

         [[0.5916, 0.2128, 0.1918, 0.7694, 0.8153, 0.5487],
          [0.1050, 0.1411, 0.5373,

In [23]:
random_multiple_dimesion.ndim

4

In [24]:
random_multiple_dimesion.shape

torch.Size([3, 4, 5, 6])

![image.png](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

In [25]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, width, color channel (R, G, B)
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.8929, 0.3307, 0.5958],
          [0.7348, 0.0869, 0.9072],
          [0.7634, 0.8176, 0.1895],
          ...,
          [0.1636, 0.4899, 0.1739],
          [0.2460, 0.3678, 0.1568],
          [0.2335, 0.2991, 0.7794]],
 
         [[0.0760, 0.5423, 0.1667],
          [0.3415, 0.6195, 0.2023],
          [0.9610, 0.2691, 0.3310],
          ...,
          [0.5267, 0.4568, 0.9323],
          [0.0959, 0.3681, 0.4394],
          [0.4433, 0.3545, 0.2927]],
 
         [[0.6730, 0.0466, 0.2428],
          [0.7665, 0.7643, 0.6429],
          [0.7700, 0.6775, 0.4882],
          ...,
          [0.1072, 0.1047, 0.6852],
          [0.6252, 0.1794, 0.6637],
          [0.2859, 0.2785, 0.7401]],
 
         ...,
 
         [[0.4230, 0.5633, 0.9175],
          [0.2057, 0.1115, 0.4664],
          [0.1283, 0.1934, 0.7511],
          ...,
          [0.8692, 0.2540, 0.2236],
          [0.0532, 0.9014, 0.2030],
          [0.4066, 0.8497, 0.8199]],
 
         [[0.6301, 0.6953, 0.4958],
          [0

In [26]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Tensor Datatypes

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

float_32_tensor.dtype, float_16_tensor

(torch.float32, tensor([3., 6., 9.], dtype=torch.float16))

In [30]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, # Data Types eg.: flot32 (Default), float16, float64, etc. used in Precision in Computer
                            device=None, # defaults to None, which uses the default tensor type eg.: "cpu", "cuda", etc
                            requires_grad=False # if True, operations performed on the tensor are recorded
                            )

float_tensor

tensor([3., 6., 9.])

In [31]:
multiplied_tensor = float_16_tensor * float_32_tensor

multiplied_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

multiplied_int_tensor = int_32_tensor * float_tensor

In [33]:
float_32_tensor.device, float_32_tensor.shape

(device(type='cpu'), torch.Size([3]))

### Manipulating Tensors
Tensor Operations includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [34]:
o_tensor = torch.tensor([1, 2, 3])
o_tensor + 10

tensor([11, 12, 13])

In [35]:
o_tensor * 10

tensor([10, 20, 30])

In [36]:
o_tensor - 10

tensor([-9, -8, -7])

In [37]:
print(torch.mul(o_tensor, 10))
print(torch.add(o_tensor, 10))
print(torch.sub(o_tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])


### Matrix Multiplication

1. Element-wise multiplication
2. Matrix Multiplication

In [38]:
# Element-wise
o_tensor * o_tensor

tensor([1, 4, 9])

In [39]:
%%time

# Matrix Multiplication
torch.matmul(o_tensor, o_tensor)

# torch.mm is same as torch.matmul

CPU times: user 348 µs, sys: 132 µs, total: 480 µs
Wall time: 593 µs


tensor(14)

## Common Errors in Deep Learning is Shape Error (Basic High School Maths)
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* *similarly, `n` numst be equal to `p`*
2. The resulting Matrix has shape `m x q` for two matrix of order `m x n` and `p x n`.


In [40]:
# Transpose of a Matrix
sample_tensor_transpose = torch.rand(3,2)
print(f"Same Matrix => {sample_tensor_transpose}")
print(f"Transpose Matrix => {sample_tensor_transpose.T}")

Same Matrix => tensor([[0.3923, 0.8353],
        [0.9061, 0.6019],
        [0.1362, 0.1218]])
Transpose Matrix => tensor([[0.3923, 0.9061, 0.1362],
        [0.8353, 0.6019, 0.1218]])


## Finding the min, max, mean, sum, etc

In [41]:
sample_tensor = torch.arange(0, 100, 10) # From, To, Length
sample_tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
# Find the min
torch.min(sample_tensor), sample_tensor.min()

(tensor(0), tensor(0))

In [43]:
# Find the max
torch.max(sample_tensor), sample_tensor.max()

(tensor(90), tensor(90))

In [44]:
# Find the mean
# Finding the mean requires the tensor to be of datatype of float32
torch.mean(sample_tensor.type(torch.float32)), sample_tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [45]:
# Find Sum
torch.sum(sample_tensor), sample_tensor.sum()

(tensor(450), tensor(450))

## Finding the position min and max

In [46]:
sample_tensor.argmin()

tensor(0)

In [47]:
sample_tensor.argmax()

tensor(9)

## Reshaping, Stacking, Squeezing, and unsqueezing tensors
* Reshaping - *Reshape an tensor to a different shape*
* View - *Return a view of an input tensor of certain shape but keep the same memory*
* Stacking - *Combining multiple tensors on top of each other (vstack) or side by side (hstack)*
* Squeeze - *Removes all `1` diminesions from a tensor*
* Unsequeeze - *Add a `1` dimension to a target tensor*
* Permute - *Return a view of the input with dimensions permuted (swapped) in a certain way*

In [48]:
# Change the shape
sample_tensor.reshape(2, 5) # <- order of new matrix must match the no. of elements with prev. matrix

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [49]:
# Change the view
sample_tensor.view(10, 1)

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [50]:
# Stack tensor
torch.stack([sample_tensor, sample_tensor, sample_tensor, sample_tensor], dim=0)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [51]:
___ = torch.rand(1, 10, 100)
__ = torch.squeeze(___, 0)
print(f"Sample Tensor => {___}")
print(f"Shape of sample Tensor => {___.shape}")
print(f"Squeeze Tensor => {__}")
print(f"Shape of Squeeze Tensor => {__.shape}")

Sample Tensor => tensor([[[0.7816, 0.8175, 0.8033, 0.5137, 0.9379, 0.0114, 0.8666, 0.8550,
          0.1573, 0.8954, 0.9071, 0.7577, 0.2906, 0.5065, 0.3337, 0.6110,
          0.7656, 0.1487, 0.5722, 0.1871, 0.5845, 0.9705, 0.2947, 0.2171,
          0.6171, 0.5064, 0.6725, 0.4791, 0.2074, 0.4923, 0.0694, 0.8055,
          0.3133, 0.3276, 0.5305, 0.1914, 0.7195, 0.9421, 0.1156, 0.6920,
          0.6739, 0.8510, 0.3449, 0.5532, 0.8928, 0.7589, 0.0620, 0.0441,
          0.8168, 0.4500, 0.8482, 0.4698, 0.1967, 0.7514, 0.5074, 0.3458,
          0.5117, 0.7127, 0.7615, 0.5367, 0.8712, 0.9794, 0.5631, 0.1263,
          0.0703, 0.2035, 0.9945, 0.2662, 0.0896, 0.6755, 0.6741, 0.4635,
          0.5264, 0.0372, 0.9447, 0.3540, 0.1449, 0.2350, 0.1707, 0.3594,
          0.7005, 0.3932, 0.0760, 0.6058, 0.5705, 0.2548, 0.5213, 0.2612,
          0.5521, 0.9288, 0.6390, 0.1829, 0.0950, 0.0691, 0.6864, 0.1178,
          0.4864, 0.5134, 0.9264, 0.8955],
         [0.5764, 0.8392, 0.2486, 0.4410, 0.2367, 0.

In [52]:
_ = __.unsqueeze(dim=0)
print(_)
print(_.shape)

tensor([[[0.7816, 0.8175, 0.8033, 0.5137, 0.9379, 0.0114, 0.8666, 0.8550,
          0.1573, 0.8954, 0.9071, 0.7577, 0.2906, 0.5065, 0.3337, 0.6110,
          0.7656, 0.1487, 0.5722, 0.1871, 0.5845, 0.9705, 0.2947, 0.2171,
          0.6171, 0.5064, 0.6725, 0.4791, 0.2074, 0.4923, 0.0694, 0.8055,
          0.3133, 0.3276, 0.5305, 0.1914, 0.7195, 0.9421, 0.1156, 0.6920,
          0.6739, 0.8510, 0.3449, 0.5532, 0.8928, 0.7589, 0.0620, 0.0441,
          0.8168, 0.4500, 0.8482, 0.4698, 0.1967, 0.7514, 0.5074, 0.3458,
          0.5117, 0.7127, 0.7615, 0.5367, 0.8712, 0.9794, 0.5631, 0.1263,
          0.0703, 0.2035, 0.9945, 0.2662, 0.0896, 0.6755, 0.6741, 0.4635,
          0.5264, 0.0372, 0.9447, 0.3540, 0.1449, 0.2350, 0.1707, 0.3594,
          0.7005, 0.3932, 0.0760, 0.6058, 0.5705, 0.2548, 0.5213, 0.2612,
          0.5521, 0.9288, 0.6390, 0.1829, 0.0950, 0.0691, 0.6864, 0.1178,
          0.4864, 0.5134, 0.9264, 0.8955],
         [0.5764, 0.8392, 0.2486, 0.4410, 0.2367, 0.3716, 0.2754, 0.0

In [53]:
___permuted = ___.permute(2, 0, 1) # Shifts axis = 0 -> 1, 1 -> 2, 2 -> 0
## Here 2, 0, 1 are the order of dim of prev tensor
___.shape, ___permuted.shape

(torch.Size([1, 10, 100]), torch.Size([100, 1, 10]))

## Indexing (Selecting data from tensors)

In [54]:
x = torch.arange(1, 19).reshape(2, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [55]:
%%time
print(x[0])
print(x[:, 0])
print(x[:, 0, 1])
print(x[:, :, 0])
print(x[0, 2, 2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 1,  2,  3],
        [10, 11, 12]])
tensor([ 2, 11])
tensor([[ 1,  4,  7],
        [10, 13, 16]])
tensor(9)
CPU times: user 0 ns, sys: 1.39 ms, total: 1.39 ms
Wall time: 1.17 ms


## Pytorch tensors & Numpy
* Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch Tensor -> NumPy -> `torch.Tensor.numpy()`

In [56]:
array = np.arange(1.0, 8.0) # Default Dtype is float64
tensor = torch.from_numpy(array)
array, tensor, tensor.type(torch.float32)

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [57]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Tensor to NumPy Array

In [58]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

In [59]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1243, 0.8268, 0.6140, 0.7496],
        [0.6599, 0.1872, 0.0944, 0.4677],
        [0.5178, 0.6845, 0.2595, 0.4416]])
tensor([[0.5606, 0.2824, 0.4806, 0.6259],
        [0.7551, 0.6128, 0.7839, 0.7156],
        [0.8469, 0.7357, 0.7677, 0.0957]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [60]:
# Let's make some random but reproducible tensor

RANDOM_SEED = 42 # Any Random Int

torch.manual_seed(RANDOM_SEED) # You need to call Random_seed mannualy for every torch.rand()
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objets on the GPU (and making faster computations)

*The below cells were run on Google Colab (GPU Configuration) because my macbook doesn't have any GPU*

*The Best practice is to use [Device Agnostic](https://pytorch.org/docs/stable/notes/cuda.html)

In [61]:
# Check GPU access with PyTorch
torch.cuda.is_available()

True

In [62]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [63]:
torch.cuda.device_count()

1

In [64]:
# create a tensor
%%time
tensor = torch.tensor([1, 2, 3], device=device)
tensor

UsageError: Line magic function `%%time` not found.


In [65]:
%%time
torch.tensor([1, 2, 3], device="cpu")

CPU times: user 66 µs, sys: 24 µs, total: 90 µs
Wall time: 88 µs


tensor([1, 2, 3])

### Moving tensors back to CPU

In [66]:
# If tensor is on GPU, can't transform to Numpy

test = tensor.cpu().numpy()

test_tensor = torch.from_numpy(test)
print(test_tensor.device)

cpu
