In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [3]:
!nvidia-smi

Sun Jul 16 11:00:11 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650        Off | 00000000:0A:00.0 Off |                  N/A |
| 40%   39C    P0              N/A /  75W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Introduction to Tensors

# Creating Tensors

In [4]:
# Scalar
# https://pytorch.org/docs/stable/tensors.html
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR_TWO = torch.tensor([[[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]],
                           [[11, 12, 13],
                            [21, 22, 23],
                            [31, 32, 33]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
TENSOR[0][1]

tensor([4, 5, 6])

In [19]:
TENSOR_TWO.shape

torch.Size([2, 3, 3])

# Random Tensors

In [20]:
# torch.rand
# https://pytorch.org/docs/stable/generated/torch.rand.html

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[3.0814e-01, 7.7888e-01, 1.5116e-01, 8.7948e-01],
        [7.2265e-01, 2.2166e-01, 5.1538e-01, 4.8568e-01],
        [6.9517e-04, 1.9116e-02, 3.8860e-02, 9.0777e-01]])

In [21]:
random_tensor.ndim

random_multiple_dimesion = torch.rand(3, 4, 5, 6)
random_multiple_dimesion

tensor([[[[0.2901, 0.7152, 0.1784, 0.8937, 0.7763, 0.0317],
          [0.6496, 0.1104, 0.6585, 0.5595, 0.0771, 0.7011],
          [0.7365, 0.1099, 0.5471, 0.7583, 0.2340, 0.0803],
          [0.3572, 0.5703, 0.0257, 0.4964, 0.1965, 0.9589],
          [0.0116, 0.0390, 0.4621, 0.7493, 0.9411, 0.3848]],

         [[0.4409, 0.4685, 0.5814, 0.6869, 0.6584, 0.9324],
          [0.4833, 0.4817, 0.4299, 0.5949, 0.1853, 0.6632],
          [0.0645, 0.5799, 0.2609, 0.0089, 0.8816, 0.5707],
          [0.1504, 0.1516, 0.8901, 0.2282, 0.7559, 0.4737],
          [0.7523, 0.0841, 0.8212, 0.4001, 0.3943, 0.3010]],

         [[0.4599, 0.1333, 0.2831, 0.1176, 0.0494, 0.7912],
          [0.8198, 0.1140, 0.3410, 0.2141, 0.8163, 0.3246],
          [0.8446, 0.4512, 0.7985, 0.4765, 0.5278, 0.5681],
          [0.3470, 0.0107, 0.9156, 0.2951, 0.0828, 0.3464],
          [0.3544, 0.3870, 0.2775, 0.0978, 0.5192, 0.6475]],

         [[0.8820, 0.1469, 0.0706, 0.4645, 0.2672, 0.7768],
          [0.5603, 0.0406, 0.2456,

In [22]:
random_multiple_dimesion.ndim

4

In [23]:
random_multiple_dimesion.shape

torch.Size([3, 4, 5, 6])

![image.png](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

In [24]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, width, color channel (R, G, B)
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[6.9846e-01, 2.0978e-01, 9.2464e-01],
          [1.3338e-01, 6.4845e-01, 1.7572e-01],
          [8.3031e-01, 6.5511e-01, 6.6541e-01],
          ...,
          [4.6958e-01, 7.4223e-01, 7.7491e-01],
          [3.7237e-01, 8.5390e-02, 8.3528e-01],
          [9.3002e-01, 2.1013e-02, 4.6784e-01]],
 
         [[9.1731e-01, 7.7749e-01, 8.3627e-01],
          [5.6689e-01, 2.5763e-01, 4.9450e-01],
          [1.4193e-01, 3.2452e-01, 5.1865e-01],
          ...,
          [6.2636e-02, 3.8970e-01, 5.8670e-01],
          [7.0374e-01, 5.9202e-01, 2.6660e-01],
          [6.8671e-01, 4.8158e-01, 7.5854e-01]],
 
         [[1.9955e-01, 8.6122e-01, 9.3777e-01],
          [7.0741e-02, 7.3495e-01, 1.9147e-01],
          [3.0942e-01, 6.0095e-01, 6.4150e-01],
          ...,
          [6.0790e-01, 5.7370e-01, 7.2988e-01],
          [7.8579e-01, 8.0935e-01, 1.7516e-01],
          [8.7639e-01, 3.5064e-01, 1.6976e-01]],
 
         ...,
 
         [[4.9061e-01, 6.5421e-01, 7.8786e-01],
          [8.0060e

In [25]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Tensor Datatypes

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

float_32_tensor.dtype, float_16_tensor

(torch.float32, tensor([3., 6., 9.], dtype=torch.float16))

In [29]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, # Data Types eg.: flot32 (Default), float16, float64, etc. used in Precision in Computer
                            device=None, # defaults to None, which uses the default tensor type eg.: "cpu", "cuda", etc
                            requires_grad=False # if True, operations performed on the tensor are recorded
                            )

float_tensor

tensor([3., 6., 9.])

In [30]:
multiplied_tensor = float_16_tensor * float_32_tensor

multiplied_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

multiplied_int_tensor = int_32_tensor * float_tensor

In [32]:
float_32_tensor.device, float_32_tensor.shape

(device(type='cpu'), torch.Size([3]))

### Manipulating Tensors
Tensor Operations includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [33]:
o_tensor = torch.tensor([1, 2, 3])
o_tensor + 10

tensor([11, 12, 13])

In [34]:
o_tensor * 10

tensor([10, 20, 30])

In [35]:
o_tensor - 10

tensor([-9, -8, -7])

In [36]:
print(torch.mul(o_tensor, 10))
print(torch.add(o_tensor, 10))
print(torch.sub(o_tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])


### Matrix Multiplication

1. Element-wise multiplication
2. Matrix Multiplication

In [37]:
# Element-wise
o_tensor * o_tensor

tensor([1, 4, 9])

In [38]:
%%time

# Matrix Multiplication
torch.matmul(o_tensor, o_tensor)

# torch.mm is same as torch.matmul

CPU times: user 201 µs, sys: 90 µs, total: 291 µs
Wall time: 198 µs


tensor(14)

## Common Errors in Deep Learning is Shape Error (Basic High School Maths)
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* *similarly, `n` numst be equal to `p`*
2. The resulting Matrix has shape `m x q` for two matrix of order `m x n` and `p x n`.


In [39]:
# Transpose of a Matrix
sample_tensor_transpose = torch.rand(3,2)
print(f"Same Matrix => {sample_tensor_transpose}")
print(f"Transpose Matrix => {sample_tensor_transpose.T}")

Same Matrix => tensor([[0.4840, 0.6339],
        [0.8057, 0.1238],
        [0.5275, 0.1955]])
Transpose Matrix => tensor([[0.4840, 0.8057, 0.5275],
        [0.6339, 0.1238, 0.1955]])


## Finding the min, max, mean, sum, etc

In [40]:
sample_tensor = torch.arange(0, 100, 10) # From, To, Length
sample_tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
# Find the min
torch.min(sample_tensor), sample_tensor.min()

(tensor(0), tensor(0))

In [42]:
# Find the max
torch.max(sample_tensor), sample_tensor.max()

(tensor(90), tensor(90))

In [43]:
# Find the mean
# Finding the mean requires the tensor to be of datatype of float32
torch.mean(sample_tensor.type(torch.float32)), sample_tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [44]:
# Find Sum
torch.sum(sample_tensor), sample_tensor.sum()

(tensor(450), tensor(450))

## Finding the position min and max

In [45]:
sample_tensor.argmin()

tensor(0)

In [46]:
sample_tensor.argmax()

tensor(9)

## Reshaping, Stacking, Squeezing, and unsqueezing tensors
* Reshaping - *Reshape an tensor to a different shape*
* View - *Return a view of an input tensor of certain shape but keep the same memory*
* Stacking - *Combining multiple tensors on top of each other (vstack) or side by side (hstack)*
* Squeeze - *Removes all `1` diminesions from a tensor*
* Unsequeeze - *Add a `1` dimension to a target tensor*
* Permute - *Return a view of the input with dimensions permuted (swapped) in a certain way*

In [47]:
# Change the shape
sample_tensor.reshape(2, 5) # <- order of new matrix must match the no. of elements with prev. matrix

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [48]:
# Change the view
sample_tensor.view(10, 1)

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [49]:
# Stack tensor
torch.stack([sample_tensor, sample_tensor, sample_tensor, sample_tensor], dim=0)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [50]:
___ = torch.rand(1, 10, 100)
__ = torch.squeeze(___, 0)
print(f"Sample Tensor => {___}")
print(f"Shape of sample Tensor => {___.shape}")
print(f"Squeeze Tensor => {__}")
print(f"Shape of Squeeze Tensor => {__.shape}")

Sample Tensor => tensor([[[0.9343, 0.6371, 0.0811, 0.7885, 0.6910, 0.9634, 0.7151, 0.9928,
          0.4662, 0.7676, 0.4376, 0.9127, 0.7861, 0.4327, 0.0641, 0.5521,
          0.4653, 0.9329, 0.1838, 0.0248, 0.8890, 0.1350, 0.7716, 0.3680,
          0.7052, 0.9866, 0.6488, 0.4282, 0.8569, 0.6170, 0.1738, 0.5201,
          0.5334, 0.3196, 0.4180, 0.3375, 0.3301, 0.7794, 0.4936, 0.2507,
          0.7233, 0.2455, 0.2289, 0.7713, 0.9852, 0.4270, 0.7038, 0.5089,
          0.9116, 0.9271, 0.6213, 0.9348, 0.9466, 0.6753, 0.1192, 0.1265,
          0.0871, 0.6194, 0.0191, 0.3968, 0.5113, 0.2007, 0.7956, 0.5590,
          0.7074, 0.3401, 0.0848, 0.0914, 0.0470, 0.9596, 0.2990, 0.7151,
          0.3730, 0.2720, 0.2614, 0.3918, 0.2381, 0.7626, 0.2794, 0.6848,
          0.9052, 0.0360, 0.5421, 0.5021, 0.7641, 0.6317, 0.3103, 0.0613,
          0.7726, 0.2828, 0.1745, 0.9686, 0.1137, 0.4297, 0.3799, 0.3143,
          0.1034, 0.4430, 0.5516, 0.8247],
         [0.4582, 0.8713, 0.7507, 0.4470, 0.3155, 0.

In [51]:
_ = __.unsqueeze(dim=0)
print(_)
print(_.shape)

tensor([[[0.9343, 0.6371, 0.0811, 0.7885, 0.6910, 0.9634, 0.7151, 0.9928,
          0.4662, 0.7676, 0.4376, 0.9127, 0.7861, 0.4327, 0.0641, 0.5521,
          0.4653, 0.9329, 0.1838, 0.0248, 0.8890, 0.1350, 0.7716, 0.3680,
          0.7052, 0.9866, 0.6488, 0.4282, 0.8569, 0.6170, 0.1738, 0.5201,
          0.5334, 0.3196, 0.4180, 0.3375, 0.3301, 0.7794, 0.4936, 0.2507,
          0.7233, 0.2455, 0.2289, 0.7713, 0.9852, 0.4270, 0.7038, 0.5089,
          0.9116, 0.9271, 0.6213, 0.9348, 0.9466, 0.6753, 0.1192, 0.1265,
          0.0871, 0.6194, 0.0191, 0.3968, 0.5113, 0.2007, 0.7956, 0.5590,
          0.7074, 0.3401, 0.0848, 0.0914, 0.0470, 0.9596, 0.2990, 0.7151,
          0.3730, 0.2720, 0.2614, 0.3918, 0.2381, 0.7626, 0.2794, 0.6848,
          0.9052, 0.0360, 0.5421, 0.5021, 0.7641, 0.6317, 0.3103, 0.0613,
          0.7726, 0.2828, 0.1745, 0.9686, 0.1137, 0.4297, 0.3799, 0.3143,
          0.1034, 0.4430, 0.5516, 0.8247],
         [0.4582, 0.8713, 0.7507, 0.4470, 0.3155, 0.9089, 0.3308, 0.6

In [52]:
___permuted = ___.permute(2, 0, 1) # Shifts axis = 0 -> 1, 1 -> 2, 2 -> 0
## Here 2, 0, 1 are the order of dim of prev tensor
___.shape, ___permuted.shape

(torch.Size([1, 10, 100]), torch.Size([100, 1, 10]))

## Indexing (Selecting data from tensors)

In [53]:
x = torch.arange(1, 19).reshape(2, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [54]:
%%time
print(x[0])
print(x[:, 0])
print(x[:, 0, 1])
print(x[:, :, 0])
print(x[0, 2, 2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 1,  2,  3],
        [10, 11, 12]])
tensor([ 2, 11])
tensor([[ 1,  4,  7],
        [10, 13, 16]])
tensor(9)
CPU times: user 542 µs, sys: 238 µs, total: 780 µs
Wall time: 621 µs


## Pytorch tensors & Numpy
* Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch Tensor -> NumPy -> `torch.Tensor.numpy()`

In [55]:
array = np.arange(1.0, 8.0) # Default Dtype is float64
tensor = torch.from_numpy(array)
array, tensor, tensor.type(torch.float32)

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [56]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Tensor to NumPy Array

In [57]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

In [58]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5105, 0.6248, 0.2527, 0.3497],
        [0.2142, 0.3317, 0.2077, 0.4521],
        [0.4315, 0.7752, 0.3646, 0.9844]])
tensor([[0.4061, 0.2215, 0.0455, 0.4992],
        [0.8008, 0.0229, 0.4003, 0.8002],
        [0.1013, 0.7716, 0.3258, 0.2777]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [59]:
# Let's make some random but reproducible tensor

RANDOM_SEED = 42 # Any Random Int

torch.manual_seed(RANDOM_SEED) # You need to call Random_seed mannualy for every torch.rand()
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objets on the GPU (and making faster computations)

*The below cells were run on Google Colab (GPU Configuration) because my macbook doesn't have any GPU*

*The Best practice is to use [Device Agnostic](https://pytorch.org/docs/stable/notes/cuda.html)

In [60]:
# Check GPU access with PyTorch
torch.cuda.is_available()

True

In [61]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [62]:
torch.cuda.device_count()

1

In [63]:
# create a tensor
%%time
tensor = torch.tensor([1, 2, 3], device=device)
tensor

UsageError: Line magic function `%%time` not found.


In [64]:
%%time
torch.tensor([1, 2, 3], device="cpu")

CPU times: user 114 µs, sys: 73 µs, total: 187 µs
Wall time: 168 µs


tensor([1, 2, 3])

### Moving tensors back to CPU

In [65]:
# If tensor is on GPU, can't transform to Numpy

test = tensor.cpu().numpy()

test_tensor = torch.from_numpy(test)
print(test_tensor.device)

cpu
