In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [3]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


# Introduction to Tensors

# Creating Tensors

In [5]:
# Scalar
# https://pytorch.org/docs/stable/tensors.html
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR_TWO = torch.tensor([[[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]],
                           [[11, 12, 13],
                            [21, 22, 23],
                            [31, 32, 33]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
TENSOR[0][1]

tensor([4, 5, 6])

In [25]:
TENSOR_TWO.shape

torch.Size([2, 3, 3])

# Random Tensors

In [27]:
# torch.rand
# https://pytorch.org/docs/stable/generated/torch.rand.html

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9638, 0.5759, 0.0662, 0.2999],
        [0.1128, 0.4797, 0.4864, 0.7427],
        [0.3365, 0.5654, 0.1367, 0.5791]])

In [30]:
random_tensor.ndim

random_multiple_dimesion = torch.rand(3, 4, 5, 6)
random_multiple_dimesion

tensor([[[[0.3198, 0.0762, 0.8776, 0.4442, 0.5458, 0.1456],
          [0.5302, 0.3176, 0.7003, 0.5111, 0.4445, 0.2902],
          [0.6461, 0.0836, 0.1105, 0.6893, 0.0585, 0.3902],
          [0.9530, 0.4654, 0.9374, 0.9975, 0.0991, 0.0789],
          [0.4917, 0.9024, 0.5662, 0.8004, 0.8082, 0.0482]],

         [[0.2828, 0.8204, 0.9609, 0.2526, 0.1142, 0.8966],
          [0.2113, 0.0473, 0.9115, 0.3478, 0.9278, 0.3632],
          [0.7052, 0.4534, 0.0234, 0.6472, 0.1132, 0.5735],
          [0.8991, 0.1330, 0.0794, 0.1258, 0.3719, 0.2696],
          [0.0030, 0.2815, 0.4071, 0.8514, 0.0544, 0.5325]],

         [[0.1718, 0.8648, 0.0048, 0.8723, 0.4494, 0.9463],
          [0.3870, 0.2510, 0.6543, 0.5403, 0.5409, 0.4593],
          [0.6791, 0.4774, 0.5171, 0.3328, 0.7543, 0.2056],
          [0.7219, 0.1247, 0.4816, 0.2440, 0.5835, 0.6133],
          [0.4975, 0.2369, 0.0117, 0.9588, 0.3505, 0.7300]],

         [[0.3406, 0.0655, 0.6645, 0.1376, 0.1003, 0.3277],
          [0.8428, 0.8015, 0.0351,

In [33]:
random_multiple_dimesion.ndim

4

In [34]:
random_multiple_dimesion.shape

torch.Size([3, 4, 5, 6])

![image.png](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

In [36]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, width, color channel (R, G, B)
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.1496, 0.7965, 0.3264],
          [0.3908, 0.8721, 0.8302],
          [0.2642, 0.9935, 0.5145],
          ...,
          [0.9990, 0.1780, 0.0392],
          [0.0906, 0.8560, 0.6487],
          [0.7705, 0.0370, 0.7331]],
 
         [[0.7951, 0.2313, 0.8508],
          [0.8227, 0.6691, 0.8471],
          [0.6129, 0.1254, 0.8569],
          ...,
          [0.2307, 0.9417, 0.8590],
          [0.3044, 0.4144, 0.0053],
          [0.1296, 0.9937, 0.9756]],
 
         [[0.8674, 0.0099, 0.4077],
          [0.6110, 0.6011, 0.4840],
          [0.4593, 0.8792, 0.7919],
          ...,
          [0.2245, 0.5014, 0.5603],
          [0.2869, 0.7610, 0.8554],
          [0.7247, 0.4443, 0.1544]],
 
         ...,
 
         [[0.0155, 0.1887, 0.8580],
          [0.6756, 0.5811, 0.6171],
          [0.3356, 0.9052, 0.7551],
          ...,
          [0.7565, 0.7621, 0.3358],
          [0.5446, 0.8325, 0.1776],
          [0.8139, 0.8473, 0.2205]],
 
         [[0.5088, 0.6047, 0.3174],
          [0

In [38]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Tensor Datatypes

In [41]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [44]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

float_32_tensor.dtype, float_16_tensor

(torch.float32, tensor([3., 6., 9.], dtype=torch.float16))

In [47]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, # Data Types eg.: flot32 (Default), float16, float64, etc. used in Precision in Computer
                            device=None, # defaults to None, which uses the default tensor type eg.: "cpu", "cuda", etc
                            requires_grad=False # if True, operations performed on the tensor are recorded
                            )

float_tensor

tensor([3., 6., 9.])

In [49]:
multiplied_tensor = float_16_tensor * float_32_tensor

multiplied_tensor

tensor([ 9., 36., 81.])

In [50]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

multiplied_int_tensor = int_32_tensor * float_tensor

In [52]:
float_32_tensor.device, float_32_tensor.shape

(device(type='cpu'), torch.Size([3]))

## Start from 2:13:10 [Youtube Video](https://youtu.be/V_xro1bcAuA)