In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
!nvidia-smi

Sat Jul 15 12:01:59 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Introduction to Tensors

# Creating Tensors

In [3]:
# Scalar
# https://pytorch.org/docs/stable/tensors.html
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR_TWO = torch.tensor([[[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]],
                           [[11, 12, 13],
                            [21, 22, 23],
                            [31, 32, 33]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[0][1]

tensor([4, 5, 6])

In [18]:
TENSOR_TWO.shape

torch.Size([2, 3, 3])

# Random Tensors

In [19]:
# torch.rand
# https://pytorch.org/docs/stable/generated/torch.rand.html

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2491, 0.5655, 0.2226, 0.1534],
        [0.3613, 0.0837, 0.9098, 0.6865],
        [0.4514, 0.5386, 0.8111, 0.1929]])

In [20]:
random_tensor.ndim

random_multiple_dimesion = torch.rand(3, 4, 5, 6)
random_multiple_dimesion

tensor([[[[0.3777, 0.9625, 0.2135, 0.5642, 0.7943, 0.1545],
          [0.2300, 0.4665, 0.6508, 0.8204, 0.4904, 0.3191],
          [0.7748, 0.0994, 0.8681, 0.6873, 0.9908, 0.4467],
          [0.4012, 0.1043, 0.7776, 0.6441, 0.1653, 0.6401],
          [0.4454, 0.8829, 0.8493, 0.1298, 0.3886, 0.2204]],

         [[0.9227, 0.6917, 0.6988, 0.1652, 0.0738, 0.6569],
          [0.8503, 0.7897, 0.7793, 0.8435, 0.2234, 0.6749],
          [0.5931, 0.6195, 0.2500, 0.9069, 0.5556, 0.3487],
          [0.9144, 0.7909, 0.7641, 0.5496, 0.2017, 0.2166],
          [0.6987, 0.0767, 0.2291, 0.8240, 0.1699, 0.7201]],

         [[0.1069, 0.7938, 0.2143, 0.9798, 0.3845, 0.9061],
          [0.3749, 0.7629, 0.8916, 0.7351, 0.5449, 0.3710],
          [0.2718, 0.5792, 0.9330, 0.1779, 0.5071, 0.0715],
          [0.3828, 0.3849, 0.6766, 0.2474, 0.3891, 0.8501],
          [0.7865, 0.6843, 0.1528, 0.0981, 0.7714, 0.2714]],

         [[0.5311, 0.5730, 0.0254, 0.8293, 0.4249, 0.8245],
          [0.3321, 0.4495, 0.8159,

In [21]:
random_multiple_dimesion.ndim

4

In [22]:
random_multiple_dimesion.shape

torch.Size([3, 4, 5, 6])

![image.png](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

In [23]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, width, color channel (R, G, B)
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.5272, 0.8493, 0.7067],
          [0.8123, 0.2822, 0.0387],
          [0.0363, 0.9368, 0.4221],
          ...,
          [0.2263, 0.6668, 0.0793],
          [0.8939, 0.5499, 0.2588],
          [0.6520, 0.9746, 0.1490]],
 
         [[0.1188, 0.6255, 0.5008],
          [0.2647, 0.0205, 0.4516],
          [0.2402, 0.1507, 0.1990],
          ...,
          [0.6643, 0.8768, 0.1065],
          [0.0873, 0.1720, 0.1651],
          [0.0717, 0.3718, 0.5767]],
 
         [[0.7934, 0.5250, 0.9419],
          [0.0235, 0.6842, 0.7345],
          [0.5330, 0.5130, 0.0390],
          ...,
          [0.9524, 0.4974, 0.1387],
          [0.5358, 0.6802, 0.9658],
          [0.2752, 0.2122, 0.5188]],
 
         ...,
 
         [[0.7991, 0.7326, 0.8770],
          [0.9426, 0.9462, 0.7970],
          [0.4146, 0.2866, 0.5397],
          ...,
          [0.4924, 0.2699, 0.0013],
          [0.1578, 0.0608, 0.4103],
          [0.5037, 0.7814, 0.0752]],
 
         [[0.9648, 0.3858, 0.6673],
          [0

In [24]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Tensor Datatypes

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

float_32_tensor.dtype, float_16_tensor

(torch.float32, tensor([3., 6., 9.], dtype=torch.float16))

In [28]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, # Data Types eg.: flot32 (Default), float16, float64, etc. used in Precision in Computer
                            device=None, # defaults to None, which uses the default tensor type eg.: "cpu", "cuda", etc
                            requires_grad=False # if True, operations performed on the tensor are recorded
                            )

float_tensor

tensor([3., 6., 9.])

In [29]:
multiplied_tensor = float_16_tensor * float_32_tensor

multiplied_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

multiplied_int_tensor = int_32_tensor * float_tensor

In [31]:
float_32_tensor.device, float_32_tensor.shape

(device(type='cpu'), torch.Size([3]))

### Manipulating Tensors
Tensor Operations includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [32]:
o_tensor = torch.tensor([1, 2, 3])
o_tensor + 10

tensor([11, 12, 13])

In [33]:
o_tensor * 10

tensor([10, 20, 30])

In [34]:
o_tensor - 10

tensor([-9, -8, -7])

In [35]:
print(torch.mul(o_tensor, 10))
print(torch.add(o_tensor, 10))
print(torch.sub(o_tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])


### Matrix Multiplication

1. Element-wise multiplication
2. Matrix Multiplication

In [36]:
# Element-wise
o_tensor * o_tensor

tensor([1, 4, 9])

In [37]:
%%time

# Matrix Multiplication
torch.matmul(o_tensor, o_tensor)

# torch.mm is same as torch.matmul

CPU times: user 1.22 ms, sys: 38 µs, total: 1.26 ms
Wall time: 1.42 ms


tensor(14)

## Common Errors in Deep Learning is Shape Error (Basic High School Maths)
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* *similarly, `n` numst be equal to `p`*
2. The resulting Matrix has shape `m x q` for two matrix of order `m x n` and `p x n`.


In [38]:
# Transpose of a Matrix
sample_tensor_transpose = torch.rand(3,2)
print(f"Same Matrix => {sample_tensor_transpose}")
print(f"Transpose Matrix => {sample_tensor_transpose.T}")

Same Matrix => tensor([[0.9694, 0.9006],
        [0.3250, 0.8531],
        [0.4222, 0.4721]])
Transpose Matrix => tensor([[0.9694, 0.3250, 0.4222],
        [0.9006, 0.8531, 0.4721]])


## Finding the min, max, mean, sum, etc

In [39]:
sample_tensor = torch.arange(0, 100, 10) # From, To, Length
sample_tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
# Find the min
torch.min(sample_tensor), sample_tensor.min()

(tensor(0), tensor(0))

In [41]:
# Find the max
torch.max(sample_tensor), sample_tensor.max()

(tensor(90), tensor(90))

In [42]:
# Find the mean
# Finding the mean requires the tensor to be of datatype of float32
torch.mean(sample_tensor.type(torch.float32)), sample_tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [43]:
# Find Sum
torch.sum(sample_tensor), sample_tensor.sum()

(tensor(450), tensor(450))

## Finding the position min and max

In [44]:
sample_tensor.argmin()

tensor(0)

In [45]:
sample_tensor.argmax()

tensor(9)

## Reshaping, Stacking, Squeezing, and unsqueezing tensors
* Reshaping - *Reshape an tensor to a different shape*
* View - *Return a view of an input tensor of certain shape but keep the same memory*
* Stacking - *Combining multiple tensors on top of each other (vstack) or side by side (hstack)*
* Squeeze - *Removes all `1` diminesions from a tensor*
* Unsequeeze - *Add a `1` dimension to a target tensor*
* Permute - *Return a view of the input with dimensions permuted (swapped) in a certain way*

In [46]:
# Change the shape
sample_tensor.reshape(2, 5) # <- order of new matrix must match the no. of elements with prev. matrix

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [47]:
# Change the view
sample_tensor.view(10, 1)

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [48]:
# Stack tensor
torch.stack([sample_tensor, sample_tensor, sample_tensor, sample_tensor], dim=0)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [49]:
___ = torch.rand(1, 10, 100)
__ = torch.squeeze(___, 0)
print(f"Sample Tensor => {___}")
print(f"Shape of sample Tensor => {___.shape}")
print(f"Squeeze Tensor => {__}")
print(f"Shape of Squeeze Tensor => {__.shape}")

Sample Tensor => tensor([[[8.1604e-02, 5.5777e-01, 5.6519e-01, 3.7949e-01, 3.2019e-01,
          1.2512e-02, 1.7232e-01, 6.1989e-01, 2.6611e-01, 8.8171e-01,
          4.3468e-01, 4.8534e-01, 6.5356e-01, 8.2544e-01, 5.5690e-03,
          7.9273e-01, 3.9011e-01, 9.1248e-01, 4.9983e-01, 1.5944e-01,
          9.3060e-01, 3.9573e-01, 9.1588e-01, 5.9542e-01, 1.6326e-01,
          6.8410e-01, 4.8002e-01, 8.4797e-01, 4.1669e-01, 8.5191e-01,
          1.2811e-01, 5.9065e-02, 5.2418e-01, 4.9123e-01, 3.2916e-01,
          7.8653e-01, 8.3126e-01, 1.2715e-01, 8.7355e-01, 7.7170e-01,
          4.6341e-01, 9.4083e-01, 7.8896e-01, 7.4822e-01, 6.8038e-01,
          7.7032e-01, 6.7850e-01, 3.8958e-01, 9.7527e-01, 3.4469e-01,
          8.1498e-01, 8.6578e-01, 6.6221e-01, 8.6281e-01, 4.5094e-01,
          7.3580e-01, 6.7423e-01, 3.5662e-01, 5.3104e-02, 9.5417e-01,
          9.4645e-01, 1.1101e-01, 6.3186e-01, 2.1569e-01, 6.7742e-01,
          6.4431e-01, 2.2300e-01, 9.5500e-01, 1.4852e-02, 8.3962e-01,
   

In [50]:
_ = __.unsqueeze(dim=0)
print(_)
print(_.shape)

tensor([[[8.1604e-02, 5.5777e-01, 5.6519e-01, 3.7949e-01, 3.2019e-01,
          1.2512e-02, 1.7232e-01, 6.1989e-01, 2.6611e-01, 8.8171e-01,
          4.3468e-01, 4.8534e-01, 6.5356e-01, 8.2544e-01, 5.5690e-03,
          7.9273e-01, 3.9011e-01, 9.1248e-01, 4.9983e-01, 1.5944e-01,
          9.3060e-01, 3.9573e-01, 9.1588e-01, 5.9542e-01, 1.6326e-01,
          6.8410e-01, 4.8002e-01, 8.4797e-01, 4.1669e-01, 8.5191e-01,
          1.2811e-01, 5.9065e-02, 5.2418e-01, 4.9123e-01, 3.2916e-01,
          7.8653e-01, 8.3126e-01, 1.2715e-01, 8.7355e-01, 7.7170e-01,
          4.6341e-01, 9.4083e-01, 7.8896e-01, 7.4822e-01, 6.8038e-01,
          7.7032e-01, 6.7850e-01, 3.8958e-01, 9.7527e-01, 3.4469e-01,
          8.1498e-01, 8.6578e-01, 6.6221e-01, 8.6281e-01, 4.5094e-01,
          7.3580e-01, 6.7423e-01, 3.5662e-01, 5.3104e-02, 9.5417e-01,
          9.4645e-01, 1.1101e-01, 6.3186e-01, 2.1569e-01, 6.7742e-01,
          6.4431e-01, 2.2300e-01, 9.5500e-01, 1.4852e-02, 8.3962e-01,
          6.9381e-01

In [51]:
___permuted = ___.permute(2, 0, 1) # Shifts axis = 0 -> 1, 1 -> 2, 2 -> 0
## Here 2, 0, 1 are the order of dim of prev tensor
___.shape, ___permuted.shape

(torch.Size([1, 10, 100]), torch.Size([100, 1, 10]))

## Indexing (Selecting data from tensors)

In [52]:
x = torch.arange(1, 19).reshape(2, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [53]:
%%time
print(x[0])
print(x[:, 0])
print(x[:, 0, 1])
print(x[:, :, 0])
print(x[0, 2, 2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 1,  2,  3],
        [10, 11, 12]])
tensor([ 2, 11])
tensor([[ 1,  4,  7],
        [10, 13, 16]])
tensor(9)
CPU times: user 4.83 ms, sys: 0 ns, total: 4.83 ms
Wall time: 5 ms


## Pytorch tensors & Numpy
* Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch Tensor -> NumPy -> `torch.Tensor.numpy()`

In [54]:
array = np.arange(1.0, 8.0) # Default Dtype is float64
tensor = torch.from_numpy(array)
array, tensor, tensor.type(torch.float32)

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [55]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Tensor to NumPy Array

In [56]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

In [57]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1052, 0.9216, 0.6712, 0.3582],
        [0.8717, 0.1191, 0.0299, 0.8420],
        [0.2476, 0.7796, 0.4216, 0.0824]])
tensor([[0.6704, 0.5558, 0.1818, 0.1108],
        [0.0818, 0.6537, 0.8927, 0.2921],
        [0.5736, 0.4108, 0.8902, 0.0725]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [58]:
# Let's make some random but reproducible tensor

RANDOM_SEED = 42 # Any Random Int

torch.manual_seed(RANDOM_SEED) # You need to call Random_seed mannualy for every torch.rand()
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objets on the GPU (and making faster computations)

*The below cells were run on Google Colab (GPU Configuration) because my macbook doesn't have any GPU*

*The Best practice is to use [Device Agnostic](https://pytorch.org/docs/stable/notes/cuda.html)

In [59]:
# Check GPU access with PyTorch
torch.cuda.is_available()

True

In [61]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [62]:
torch.cuda.device_count()

1

In [70]:
# create a tensor
%%time
tensor = torch.tensor([1, 2, 3], device=device)
tensor

CPU times: user 224 µs, sys: 15 µs, total: 239 µs
Wall time: 245 µs


tensor([1, 2, 3], device='cuda:0')

In [69]:
%%time
torch.tensor([1, 2, 3], device="cpu")

CPU times: user 98 µs, sys: 10 µs, total: 108 µs
Wall time: 99.2 µs


tensor([1, 2, 3])

### Moving tensors back to CPU

In [81]:
# If tensor is on GPU, can't transform to Numpy

test = tensor.cpu().numpy()

test_tensor = torch.from_numpy(test)
print(test_tensor.device)

cpu
