In [2]:
import numpy as np

# Set seed for reproducibility
np.random.seed(seed=1234)

# Basics

![Basics of Numpy](https://madewithml.com/static/images/foundations/numpy/tensors.png)

In [3]:
# Scalar
x = np.array(6)
print(f"x: {x}")
print(f"x ndim: {x.ndim}") # number of dimensions
print(f"x shape: {x.shape}") # dimesions
print(f"x size: {x.size}") # size of elements
print(f"x dtype: {x.dtype}") # data type

x: 6
x ndim: 0
x shape: ()
x size: 1
x dtype: int64


In [4]:
# Vector
x = np.array([1.3, 2.2, 1.7])

print(f"x: {x}")
print(f"x ndim: {x.ndim}") # number of dimensions
print(f"x shape: {x.shape}") # dimesions
print(f"x size: {x.size}") # size of elements
print(f"x dtype: {x.dtype}") # data type

x: [1.3 2.2 1.7]
x ndim: 1
x shape: (3,)
x size: 3
x dtype: float64


In [5]:
# Matrix
x = np.array([[1, 2], [3, 4]])

print(f"x: {x}")
print(f"x ndim: {x.ndim}") # number of dimensions
print(f"x shape: {x.shape}") # dimesions
print(f"x size: {x.size}") # size of elements
print(f"x dtype: {x.dtype}") # data type

x: [[1 2]
 [3 4]]
x ndim: 2
x shape: (2, 2)
x size: 4
x dtype: int64


In [6]:
# 3-D Tensor
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"x: {x}")
print(f"x ndim: {x.ndim}") # number of dimensions
print(f"x shape: {x.shape}") # dimesions
print(f"x size: {x.size}") # size of elements
print(f"x dtype: {x.dtype}") # data type

x: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim: 3
x shape: (2, 2, 2)
x size: 8
x dtype: int64


NumPy also comes with several functions that allow us to create tensors quickly.

In [7]:
# Functions
print(f"np.zeros((2, 2)):\n {np.zeros((2, 2))}")
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2))) # identity matrix
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2, 2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


# Indexing

We can extract specific values from our tensors using indexing.

> Keep in mind that when indexing the row and column, indices start at `0`. And like indexing with lists, we can use negative indices as well (where `-1` is the last item).

![Indexing](https://madewithml.com/static/images/foundations/numpy/indexing.png)


In [8]:
# Indexing
x = np.array([1, 2, 3])
print(f"x: {x}")
print(f"x[0]: {x[0]}")
x[0] = 0
print(f"x: {x}")

x: [1 2 3]
x[0]: 1
x: [0 2 3]


In [9]:
# Slicing
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(f"x: {x}")
print(f"x column 1: {x[:, 1]}")
print(f"x row 0: {x[0, :]}")
print(f"x row 0, 1 & cols 1, 2:\n{x[0, :]}  {x[1, :]}  {x[:, 1]}  {x[:, 2]}")

x: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1: [ 2  6 10]
x row 0: [1 2 3 4]
x row 0, 1 & cols 1, 2:
[1 2 3 4]  [5 6 7 8]  [ 2  6 10]  [ 3  7 11]


In [10]:
# Integer array indexing
print (x)
rows_to_get = np.array([0, 1, 2])
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
# Combine sequences above to get values to get
print ("indexed values: ", x[rows_to_get, cols_to_get]) # (0, 0), (1, 2), (2, 1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [11]:
# Boolean array indexing
x = np.array([[1, 2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2)
print ("x[x > 2]:\n", x[x > 2])

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


# Airthmetic

In [12]:
# Basic Math
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


# Dot Product
One of the most common NumPy operations we’ll use in machine learning is matrix multiplication using the dot product. Suppose we wanted to take the dot product of two matrices with shapes `[2 X 3]` and `[3 X 2]`. We take the rows of our first matrix (2) and the columns of our second matrix (2) to determine the dot product, giving us an output of `[2 X 2]`. The only requirement is that the inside dimensions match, in this case the first matrix has 3 columns and the second matrix has 3 rows.

![Dot Product](https://madewithml.com/static/images/foundations/numpy/dot.gif)

In [13]:
# Dot product
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
c = a.dot(b)
print (f"{a.shape} · {b.shape} = {c.shape}")
print (c)

(2, 3) · (3, 2) = (2, 2)
[[ 58.  64.]
 [139. 154.]]


# Axis Operations

We can also do operations across a specific axis.

![Axis Operations](https://madewithml.com/static/images/foundations/numpy/axis.gif)

In [14]:
# Sum across a dimension
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum axis=0: ", np.sum(x, axis=0)) # sum across rows
print ("sum axis=1: ", np.sum(x, axis=1)) # sum across columns

[[1 2]
 [3 4]]
sum all:  10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


In [15]:
# Min/max
x = np.array([[1,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0: ", x.min(axis=0))
print ("min axis=1: ", x.min(axis=1))

min:  1
max:  6
min axis=0:  [1 2 3]
min axis=1:  [1 4]


# Broadcast

What happens when we try to do operations with tensors with seemingly incompatible shapes? Their dimensions aren’t compatible as is but how does NumPy still gives us the right result? This is where broadcasting comes in. The scalar is broadcast across the vector so that they have compatible shapes.

![Broadcasting](https://madewithml.com/static/images/foundations/numpy/broadcast.png)


In [16]:
# Broadcasting
x = np.array([1,2]) # vector
y = np.array(3) # scalar
z = x + y
print ("z:\n", z)

z:
 [4 5]


# Gotchas

In the situation below, what is the value of `c` and what are its dimensions?

In [17]:
a = np.array((3, 4, 5))
b = np.expand_dims(a, axis=1)
c = a + b

In [18]:
a.shape # (3,)
b.shape # (3, 1)
c.shape # (3, 3)
print (c)

[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


How can we fix this? We need to be careful to ensure that `a` is the same shape as `b` if we don't want this unintentional broadcasting behavior.

In [19]:
a = a.reshape(-1, 1)
a.shape # (3, 1)
c = a + b
c.shape # (3, 1)
print (c)

[[ 6]
 [ 8]
 [10]]


This kind of unintended broadcasting happens more often then you'd think because this is exactly what happens when we create an array from a list. So we need to ensure that we apply the proper reshaping before using it for any operations.

In [20]:
a = np.array([3, 4, 5])
a.shape # (3,)
a = a.reshape(-1, 1)
a.shape # (3, 1)

(3, 1)