# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
tensor = torch.rand(7,7)
tensor, tensor.shape


(tensor([[0.3786, 0.7593, 0.8916, 0.6555, 0.0972, 0.0778, 0.0597],
         [0.2964, 0.5742, 0.0413, 0.3362, 0.2790, 0.1167, 0.6425],
         [0.3551, 0.6358, 0.7851, 0.9696, 0.7313, 0.6627, 0.1839],
         [0.6238, 0.9435, 0.8472, 0.0135, 0.1828, 0.9029, 0.6394],
         [0.5520, 0.1507, 0.3463, 0.9733, 0.2778, 0.9692, 0.8798],
         [0.7046, 0.1174, 0.3369, 0.6700, 0.3830, 0.6397, 0.4669],
         [0.1705, 0.1415, 0.9175, 0.1097, 0.9673, 0.4493, 0.4257]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
random_tensor = torch.rand(1, 7)

# Perform matrix multiplication
torch.matmul(tensor, random_tensor.T)


tensor([[1.6117],
        [1.0788],
        [2.2642],
        [2.7997],
        [2.1671],
        [1.8917],
        [1.7768]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
RANDOM_SEED = 0


# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(1, 7)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


# Matrix multiply tensors
torch.matmul(random_tensor_A, random_tensor_B.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[ True,  True,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [14]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.cuda.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(2, 3, device=device)

torch.cuda.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(2, 3, device=device)

print(random_tensor_C)
print(random_tensor_D)


tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
matmul = torch.matmul(random_tensor_C, random_tensor_D.T)
matmul, matmul.shape

(tensor([[0.9792, 0.8358],
         [0.8358, 1.4578]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
max = matmul.max()

# Find min
min = matmul.min()

max, min


(tensor(1.4578, device='cuda:0'), tensor(0.8358, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [19]:
# Find arg max
argmax = matmul.argmax()


# Find arg min
argmin = matmul.argmin()

argmax, argmin


(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
# Set seed
RANDOM_SEED = 4567

# Create random tensor
torch.cuda.manual_seed(RANDOM_SEED) if torch.cuda.is_available() else torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(1, 1, 1, 10, device=device)


# Remove single dimensions
squeezed_tensor = torch.squeeze(random_tensor_E)

# Print out tensors and their shapes
random_tensor_E, random_tensor_E.shape, squeezed_tensor, squeezed_tensor.shape


(tensor([[[[0.8639, 0.8844, 0.1540, 0.7392, 0.0268, 0.0378, 0.1185, 0.8022,
            0.7214, 0.8583]]]], device='cuda:0'),
 torch.Size([1, 1, 1, 10]),
 tensor([0.8639, 0.8844, 0.1540, 0.7392, 0.0268, 0.0378, 0.1185, 0.8022, 0.7214,
         0.8583], device='cuda:0'),
 torch.Size([10]))